---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esrally-geonames-tournament-entrypoint-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    sleep infinity

---
apiVersion: batch/v1
kind: Job
metadata:
  name: esrally-geonames-tournament
spec:
  template:
    spec:
      containers:
      - name: esrally
        image: elastic/rally
        command:
          - /bin/entrypoint.sh
        volumeMounts:
          - name: configmap-tournament-volume
            mountPath: /bin/entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          - name: configmap-volume
            mountPath: /rally/.rally/rally.ini
            readOnly: true
            subPath: rally.ini
      volumes:
        - name: configmap-volume
          configMap:
            defaultMode: 0755
            name: esrally-geonames-entrypoint-configmap
        - name: configmap-tournament-volume
          configMap:
            defaultMode: 0755
            name: esrally-geonames-tournament-entrypoint-configmap
      restartPolicy: Never
  backoffLimit: 4
