---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esrally-geonames-metricstore-entrypoint-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    esrally race \
    --track=geonames \
    --target-hosts elasticsearch-master:9200 \
    --pipeline=benchmark-only \
    --test-mode
  rally.ini: |-
    [meta]
    config.version = 17
    
    [system]
    env.name = local
    
    [node]
    root.dir = /rally/.rally/benchmarks
    src.root.dir = /rally/.rally/benchmarks/src
    
    [source]
    remote.repo.url = https://github.com/elastic/elasticsearch.git
    elasticsearch.src.subdir = elasticsearch
    
    [benchmarks]
    local.dataset.cache = /rally/.rally/benchmarks/data
    
    [reporting]
    datastore.type = elasticsearch
    datastore.host = metricstore-master
    datastore.port = 9200
    datastore.secure = false
    datastore.user =
    datastore.password =
    datastore.number_of_replicas = 0

    [tracks]
    default.url = https://github.com/elastic/rally-tracks
    
    [teams]
    default.url = https://github.com/elastic/rally-teams
    
    [defaults]
    preserve_benchmark_candidate = false

    [distributions]
    release.cache = true

---
apiVersion: batch/v1
kind: Job
metadata:
  name: esrally-geonames-metricstore
spec:
  template:
    spec:
      containers:
      - name: esrally
        image: elastic/rally
        command:
          - /bin/entrypoint.sh
        volumeMounts:
          - name: configmap-volume
            mountPath: /bin/entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
          - name: configmap-volume
            mountPath: /rally/.rally/rally.ini
            readOnly: true
            subPath: rally.ini
      volumes:
        - name: configmap-volume
          configMap:
            defaultMode: 0755
            name: esrally-geonames-metricstore-entrypoint-configmap
      restartPolicy: Never
  backoffLimit: 4
