---

daemonset.enabled: false
imageTag: 8.5.1

deployment:
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: elasticsearch
        enabled: true
        xpack.enabled: true
        period: 10s
        hosts: ["https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}"]
        ssl.enabled: true
        ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
      output.elasticsearch:
        hosts: 'https://${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
        ssl.enabled: true
        ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
      setup.template.settings:
        index.number_of_replicas: 0
